# Generated by Django 5.2 on 2025-04-21 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('activity_field', models.CharField(choices=[('IT', 'IT'), ('Education', 'Education'), ('Bank', 'Bank'), ('Medical', 'Medical'), ('Telecom', 'Telecom'), ('Other', 'Other')], max_length=50)),
                ('storage_needs', models.FloatField()),
                ('supports_encryption', models.BooleanField()),
                ('cpu_speed', models.FloatField()),
                ('price_per_hour', models.FloatField()),
                ('service_model_score', models.IntegerField()),
                ('recommended_provider', models.CharField(max_length=100)),
                ('provider_details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cloud Recommendation',
                'verbose_name_plural': 'Cloud Recommendations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
